### ISSUE TITLE
Rolling Up Cross Validation Results

### ISSUE THREAD

**Issue by sgodil** [RexYing/diffpool#18]
Thanks for providing the repo. I was going through the code and couldn't understand why the code is averaging the results across all the cross validation sets per epoch and then picking the max? 

I would think we would want to pick the max accuracy from each cross validation run and then average the best values from each run?

**Comment by LYF14020510036** [comment]
Hello, I am a beginner, graph classification evaluation is like author's code calculation or as you. Is it just validation set evaluation?

**Comment by RexYing** [comment]
Hi sorry for the late reply as I was working on other projects. See #17
