### ISSUE TITLE
Typo in encoder.py causes nan

### ISSUE THREAD

**Issue by shirley-wu** [RexYing/diffpool#23]
Hi, thanks for your codes. I think in encoder.py [line 383](https://github.com/RexYing/diffpool/blob/master/encoders.py#L383), ```pred_adj = torch.min(pred_adj, torch.Tensor(1).cuda())``` should be ```pred_adj = torch.min(pred_adj, torch.Tensor([1, ]).cuda())```. I'm using PyTorch 1.1.0, and ```torch.Tensor(1).cuda())``` will create a random tensor of size 1. Sometimes this will lead to negative pred_adj, and causes nan in log function.

**Comment by RexYing** [comment]
thanks for pointing it out. I fixed it along with other compatibility issues with pytorch 1.1+. Originally it was using pytorch 0.3.
