### ISSUE TITLE
Typo in example.sh

### ISSUE THREAD

**Issue by rutzeng** [RexYing/diffpool#3]
Hi,

I'm trying your code by running [example.sh](https://github.com/RexYing/diffpool/blob/master/example.sh) and found the argument `--label-classes` should be `--num-classes` according to `arg_parse` function in [train.py](https://github.com/RexYing/diffpool/blob/master/train.py).
You may consider to fix the typo.

Best,
Ruochun

**Comment by RexYing** [comment]
Thanks fixed.
