### ISSUE TITLE
code for auxiliary link prediction objective

### ISSUE THREAD

**Issue by liun-online** [RexYing/diffpool#30]
hi, thanks your code!
in your code, you use the auxiliary link prediction objective to reconstruct the adj, and the relevant code is in encoders.py.
in encoders.py line 383, you try to compare every element of pred_adj and 1 to ensure they are less than 1, which can successfully calculate torch.log in the line 387.
however, torch.Tensor(1) means generate a random tensor scalar, not 1. maybe try  torch.Tensor([1])
that's a tiny mistake in my opinion. Or ,I'm wrong!
wish your reply!

**Comment by RexYing** [comment]
Thanks for pointing that out! I have made the changes.
Also updated to support networkx 2.4 and pytorch 1.4.0
