### ISSUE TITLE
How to set features for REDDIT-12k and COLLAB?

### ISSUE THREAD

**Issue by VoVAllen** [RexYing/diffpool#7]
I found on this [website](https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets), REDDIT-12k and COLLAB neither has node label nor node attribute. How do you set the node feature for training?

Also in your paper, you mentioned Appendix A but I couldn't find it anywhere. How can I find it?

Thanks!

**Comment by RexYing** [comment]
Hi,

you can use constant features (say, a vector of 10 ones). 
Thanks for pointing that out. I think I accidentally removed it on arxiv when updating NeurIPS template. Will update soon again.

Best,

**Comment by VoVAllen** [comment]
Thanks!
