### ISSUE TITLE
Auxiliary Link Prediction Objective and Entropy Regularization?

### ISSUE THREAD

**Issue by markcheung** [RexYing/diffpool#8]
I'm trying to understand the code after reading the paper:

1) How is Auxiliary Link Prediction Objective calculated? Is it using Frobenius norm as described in the paper? It seems to be nll_loss instead.

2) Where is the Entropy Regularization?

Thanks!

**Comment by RexYing** [comment]
1. Yes we use NLL instead, since Frobenius norm / L2 loss is harder to train in experiments

2. I'll add ent later. It's merged from another repo and I didn't put that in. 
It's just a sum of row-wise entropy of the assignment matrix

**Comment by markcheung** [comment]
Thanks.

**Comment by usherbob** [comment]
Hi, Rex. Thanks for sharing your code. But I think you should mention NLL loss in your paper. At first, I did not find your diffpool repo, and tried to reproduce your code with L2 loss. It really confused me a lot since the model always went to NaN, then I had to remove the LP loss.

**Comment by usherbob** [comment]
> Thanks.
Hi, mark, did you figure it out the calculation of the Link Prediction loss. Could you give me a detailed explanation? Thanks.
